---

- name: Check slurm hostlist
  hosts: testohpc_login
  tasks:
  - name: Submit a test job
    command: sbatch --wrap hostname --parsable
    register: job

  - name: Allow some time for the job to complete
    pause:
      seconds: 10

  - name: Query sacct for job that was submitted
    command: sacct -j {{ job.stdout }} -p
    register: sacct

  - name: Check that job is in database
    vars:
      record: "{{ sacct.stdout_lines[1].split('|') }}"
    assert:
      # Expected: JobID|JobName|Partition|Account|AllocCPUS|State|ExitCode|
      that:
        - record[0] == job.stdout
        - record[5] == "COMPLETED"
      fail_msg: "FAILED - actual value: {{ sacct.stdout_lines[1] }}"
