stages:
  - build

variables:
  GIT_LFS_SKIP_SMUDGE: "1" # To skip auto LFS checkout

.build_template: &build_definition
  stage: build
  script:
    # Export Secrets
    - export NEXUS_DOMAIN_NAME=$NEXUS_DOMAIN_NAME
    - export NEXUS_DOMAIN_SSL_DHPARAMS=$NEXUS_DOMAIN_SSL_DHPARAMS
    - export NEXUS_DOMAIN_SSL_CERTIFICATE_PUBLIC_KEY=$NEXUS_DOMAIN_SSL_CERTIFICATE_PUBLIC_KEY
    - export NEXUS_DOMAIN_SSL_CERTIFICATE_PRIVATE_KEY=$NEXUS_DOMAIN_SSL_CERTIFICATE_PRIVATE_KEY
    - export NEXUS_HETZNER_STORAGE_BOX_URL=$NEXUS_HETZNER_STORAGE_BOX_URL
    - export NEXUS_HETZNER_STORAGE_BOX_USERNAME=$NEXUS_HETZNER_STORAGE_BOX_USERNAME
    - export NEXUS_HETZNER_STORAGE_BOX_PASSWORD=$NEXUS_HETZNER_STORAGE_BOX_PASSWORD
    - export GITLAB_RUNNER_ROCKY_8_TOKEN=$GITLAB_RUNNER_ROCKY_8_TOKEN
    - export GITLAB_RUNNER_ROCKY_9_TOKEN=$GITLAB_RUNNER_ROCKY_9_TOKEN

    # Determine if tag push
    - |
      if [[ "${CI_COMMIT_REF_NAME}" == v* ]]; then
        export IS_TAG_PUSH=true
      else
        export IS_TAG_PUSH=false
      fi

    # Extract version from git tag or default to 'dev'
    - |
      if [[ "${IS_TAG_PUSH}" == "true" ]]; then
        export VERSION=${CI_COMMIT_REF_NAME#v}
      else
        export VERSION=dev
      fi

    # Build based on matrix type
    - ./make-image.sh -k $(pwd)/kickstarts/r8/${BUILD_TYPE}-rocky-base.ks -i ${BUILD_TYPE}-rocky-8.8-x86_64-${VERSION} -p "${PRIVATE_KEY}" -f ${BUILD_FORMAT}
    # Similarly for live-pxe and disk-infra...

    # Upload artifact
    - |
      case "${BUILD_FORMAT}" in
          rootfs)
              export FILE_EXTENSION=tar.gz
              ;;
          iso)
              export FILE_EXTENSION=iso
              ;;
          squashfs)
              export FILE_EXTENSION=img
              ;;
      esac

      curl --upload-file build/kickstarts/images/rocky-${BUILD_TYPE}-x86_64-${VERSION}.${FILE_EXTENSION} \
        -u $NEXUS_USER:$NEXUS_PASS https://nexus.superclustr.net/repository/superclustr-binaries/${BUILD_TYPE}/rocky/8.8/x86_64/

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^v/'

  variables:
    PRIVATE_KEY: $PRIVATE_KEY
    NEXUS_USER: $NEXUS_USER
    NEXUS_PASS: $NEXUS_PASS

  tags:
    - rocky-8.8

client:
  <<: *build_definition
  variables:
    BUILD_TYPE: client
    BUILD_FORMAT: rootfs

pxe:
  <<: *build_definition
  variables:
    BUILD_TYPE: pxe
    BUILD_FORMAT: iso

infra:
  <<: *build_definition
  variables:
    BUILD_TYPE: infra
    BUILD_FORMAT: iso
