stages:
  - build

variables:
  GIT_LFS_SKIP_SMUDGE: "1" # To skip auto LFS checkout

.build_template: &build_definition
  stage: build
  script:
    # Export Secrets
    - export NEXUS_DOMAIN_NAME=$NEXUS_DOMAIN_NAME
    - export NEXUS_DOMAIN_SSL_DHPARAMS=$NEXUS_DOMAIN_SSL_DHPARAMS
    - export NEXUS_DOMAIN_SSL_CERTIFICATE_PUBLIC_KEY=$NEXUS_DOMAIN_SSL_CERTIFICATE_PUBLIC_KEY
    - export NEXUS_DOMAIN_SSL_CERTIFICATE_PRIVATE_KEY=$NEXUS_DOMAIN_SSL_CERTIFICATE_PRIVATE_KEY
    - export NEXUS_HETZNER_STORAGE_BOX_URL=$NEXUS_HETZNER_STORAGE_BOX_URL
    - export NEXUS_HETZNER_STORAGE_BOX_USERNAME=$NEXUS_HETZNER_STORAGE_BOX_USERNAME
    - export NEXUS_HETZNER_STORAGE_BOX_PASSWORD=$NEXUS_HETZNER_STORAGE_BOX_PASSWORD
    - export GITLAB_RUNNER_ROCKY_8_TOKEN=$GITLAB_RUNNER_ROCKY_8_TOKEN
    - export GITLAB_RUNNER_ROCKY_9_TOKEN=$GITLAB_RUNNER_ROCKY_9_TOKEN

    # Rescan all SCSI devices dynamically
    - for host in /sys/class/scsi_host/*; do sudo sh -c "echo '- - -' > ${host}/scan"; done
    # Resize the physical LVM volume
    - sudo pvresize /dev/vda5
    # Check available space in the volume group and resize the logical volume
    - sudo lvresize -l +100%FREE /dev/rocky/root
    # Resize the XFS filesystem
    - sudo xfs_growfs /dev/rocky/root

    # Determine if tag push
    - |
      if [[ "${CI_COMMIT_REF_NAME}" == v* ]]; then
        export IS_TAG_PUSH=true
      else
        export IS_TAG_PUSH=false
      fi

    # Extract version from git tag or default to 'dev'
    - |
      if [[ "${IS_TAG_PUSH}" == "true" ]]; then
        export VERSION=${CI_COMMIT_REF_NAME#v}
      else
        export VERSION=dev
      fi

    # Build based on matrix type
    - ./make-image.sh -k rocky-live-client-base.ks -i rocky-live-client-x86_64-${VERSION} -p "${PRIVATE_KEY}"
    # Similarly for live-pxe and disk-infra...

    # Upload artifact
    - |
      if [[ "${IS_TAG_PUSH}" == "true" ]]; then
        curl --upload-file out/rocky-${BUILD_TYPE}-x86_64-${VERSION}.iso -u $NEXUS_USER:$NEXUS_PASS https://nexus.superclustr.net/repository/superclustr-binaries/directory=${BUILD_TYPE}/x86_64/
      fi

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_TAG =~ /^v/'

  variables:
    PRIVATE_KEY: $PRIVATE_KEY
    NEXUS_USER: $NEXUS_USER
    NEXUS_PASS: $NEXUS_PASS

  tags:
    - rocky-8

live-client:
  <<: *build_definition
  variables:
    BUILD_TYPE: live-client

live-pxe:
  <<: *build_definition
  variables:
    BUILD_TYPE: live-pxe

disk-infra:
  <<: *build_definition
  variables:
    BUILD_TYPE: disk-infra

