---

- name: Configure Repositories
  block:
    - include_tasks: repositories.yml
  tags: repositories

- name: Install Packages
  block:
    - include_tasks: install.yml
  tags: install

- name: Configure Packages
  block:
    - include_tasks: configure.yml
  tags: configure

- name: Start Services
  block:
    - include_tasks: start.yml
  tags: start

...
