---

- name: Check slurm hostlist
  hosts: testohpc_login
  vars:
    expected_sinfo: | # NB part2 is default (*), as slurm.conf.j2 says both are so last wins
      testohpc-part1-0      1     part1  idle
      testohpc-part1-1      1     part1  idle
      testohpc-part2-0      1     part2* idle
      testohpc-part2-1      1     part2* idle
  tasks:
  - name: Get slurm partition info
    command: sinfo -h sinfo --Node -S "#P,+N" # node-oriented output, sort by partition in order defined in slurm.conf then increasing node name
    register: sinfo
  - name: 
    assert:
      that: "sinfo.stdout.split() == expected_sinfo.split()"
      fail_msg: "FAILED - got {{ sinfo.stdout.split() }} expected {{ expected_sinfo.split() }}"
