---
- name: Converge
  hosts: all
  vars:
    openhpc_enable:
      batch: true
      runtime: true
    openhpc_slurm_service_started: false
    openhpc_slurm_control_host: testohpc-login-0
    openhpc_slurm_partitions:
      - name: "compute"
    openhpc_cluster_name: testohpc
    openhpc_slurm_configless: true
    openhpc_munge_key: "{{ specified_munge_key.content | b64decode }}"
  tasks:
    - name: Generate munge key on ansible control host (so can verify)
      command: "dd if=/dev/urandom of=/tmp/ansible-role-openhpc-test7 bs=1 count=1024" # can't use tmpfile as not idempotent
      args:
        creates: "/tmp/ansible-role-openhpc-test7"
      delegate_to: localhost

    - name: Get generated munge key
      slurp:
        src: /tmp/ansible-role-openhpc-test7
      delegate_to: localhost
      register: specified_munge_key

    - name: "Include ansible-role-openhpc"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
