---
# This playbook deploys all applications

###########################
# Docker Swarm Deployment #
###########################

- name: Deploy Docker Swarm
  shell: docker swarm init
  when: ansible_distribution in ['Rocky', 'AlmaLinux', 'OracleLinux']
  tags: docker-deploy

...