---
# This playbook deploys all applications

###########################
# Docker Swarm Deployment #
###########################

- name: Deploy Docker Swarm
  shell: docker swarm init --advertise-addr {{ ansible_default_ipv4.address }}
  when: ansible_distribution in ['Rocky', 'AlmaLinux', 'OracleLinux']
  tags: docker-deploy

...
