---
# This playbook installs all necessary packages

######################
# Slurm Installation #
######################

- name: Install Slurm Packages
  dnf:
    name: "{{ slurm_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: slurm-install

#######################
# Docker Installation #
#######################

- name: Ensure runc is not installed.
  package:
    name: runc
    state: absent

- name: Ensure container-selinux is installed.
  package:
    name: container-selinux
    state: present

- name: Ensure containerd.io is installed.
  package:
    name: containerd.io
    state: present

- name: Install Docker Packages
  dnf:
    name: "{{ docker_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: docker-install

- name: Initialize Docker Swarm Mode
  shell: docker swarm init
  when: ansible_distribution in ['Rocky', 'AlmaLinux', 'OracleLinux']
  tags: docker-config

#######################
# BeeGFS Installation #
#######################

- name: Install BeeGFS Packages
  dnf:
    name: "{{ beegfs_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: beegfs-install

#######################
# ConMan Installation #
#######################

- name: Install ConMan (Console Manager) packages
  dnf:
    name: "{{ conman_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: conman-install

- name: Ensure the ConMan configuration exists but is empty
  file:
    path: /etc/conman.conf
    state: touch
    mode: '0644'
  tags: conman-config

########################
# Genders Installation #
########################

- name: Install Genders Packages
  dnf:
    name: "{{ genders_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: genders-install

- name: Ensure the Genders config file exists but is empty
  file:
    path: /etc/genders
    state: touch
    mode: '0644'
  tags: genders-config

####################
# NHC Installation #
####################

- name: Install NHC (Node Health Checker) Packages
  dnf:
    name: "{{ nhc_packages | reject('eq', '') }}"
    install_weak_deps: false
  tags: nhc-install

- name: Ensure NHC is registered as Slurm's health check program
  blockinfile:
    path: /etc/slurm/slurm.conf
    block: |
      HealthCheckProgram=/usr/sbin/nhc
      HealthCheckInterval=300
  tags: nhc-config

...
