
---
# This playbook configures and starts packages in the os init system 

- name: Flush handler
  # As the subsequent "ensure" tasks are all no-op to check if any services have bounced
  meta: flush_handlers 

- name: Ensure Munge state
  systemd:
    name: munge
    enabled: true
    state: started

- name: Ensure slurmctld state
  systemd:
    name: slurmctld
    enabled: true
    state: started

- name: Ensure slurmrestd state
  systemd:
    name: slurmrestd
    enabled: true
    state: started

- name: Ensure docker state
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: docker-service

- name: Ensure beegfs-helperd state
  systemd:
    name: beegfs-helperd
    enabled: yes
    state: started
  tags: beegfs-service

- name: Ensure beegfs-client state
  systemd:
    name: beegfs-client
    enabled: yes
    state: started
  ignore_errors: true # Broken, disabled as cannot build kernel module without kernel-devel
  tags: beegfs-service

- name: Ensure conman state
  systemd:
    name: conman
    enabled: yes
    state: started
  ignore_errors: true # Broken, disabled as ConMan needs additional configuration before it can be used ans we are not sure what to use if for yet
  tags: conman-service