---

- hosts: testohpc_control
  tasks:
  - name: Check both compute nodes are listed and compute-0 is up
    shell: 'sinfo --noheader --Node --format="%P,%a,%l,%D,%t,%N"' # using --format ensures we control whitespace
    register: sinfo
  - assert:                        # PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
      that: "sinfo.stdout_lines == ['compute*,up,60-00:00:00,1,idle,testohpc-compute-0','compute*,up,60-00:00:00,1,unk*,testohpc-compute-1']" # NB: -1 goes 'down' after a while!
      fail_msg: "FAILED - actual value: {{ sinfo.stdout_lines }}"
  - name: Check login nodes in config
    command: "grep NodeName={{ item }} /etc/slurm/slurm.conf"
    loop: "{{ groups['testohpc_login'] }}"
