---

# NB this isn't a very good test but with only a compute node there's not much which can be checked!
- name: Check slurmd configuration
  hosts: all
  tasks:
  - name: Get slurmd config
    command: systemctl show slurmd
    register: systemctl_slurmd
  - assert:
      that: "'EnvironmentFiles=/etc/sysconfig/slurmd' in systemctl_slurmd.stdout"
      fail_msg: "FAILED - no reference to /etc/sysconfig/slurmd in slurmd config"
  - name: Get specified munge key
    slurp:
      src: /tmp/ansible-role-openhpc-test7
    register: specified_munge_key
    delegate_to: localhost

  - name: Get actual munge key
    slurp:
      src: /etc/munge/munge.key
    register: actual_munge_key

  - assert:
      that: specified_munge_key.content | b64decode == actual_munge_key.content | b64decode
      fail_msg: |
        munge key on node does not match specified one:
        specified:
        {{ specified_munge_key.content }}

        actual:
        {{ actual_munge_key.content }}
