name: Main

on: 
  push:
    branches: 
      - main

jobs:
  build:
    name: Build ${{ matrix.build_type }} Image
    runs-on: self-hosted
    strategy:
      matrix:
        build_type: ["client", "pxe"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Extract version from git tag
      run: echo "VERSION=$(echo $GITHUB_REF | sed 's/refs\/tags\/v//')" >> $GITHUB_ENV

    - name: Build ${{ matrix.build_type }}
      run: sudo ./make-image.sh -k rocky-live-${{ matrix.build_type }}-base.ks -i rocky-${{ matrix.build_type }}-live-${{ env.VERSION }}-x86_64 -d

    - name: Upload artifact
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://nexus.superclustr.net
        username: ${{ secrets.NEXUS_USER }}
        password: ${{ secrets.NEXUS_PASS }}
        format: raw
        repository: superclustr-binaries
        coordinates: groupId=net.superclustr artifactId=rocky-${{ matrix.build_type }}-live version=${{ env.VERSION }}
        assets: extension=iso
        filename: out/rocky-${{ matrix.build_type }}-live-${{ env.VERSION }}-x86_64.iso
