name: Main

on: 
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Images
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

#    Only if you run this Job on a non amd64 image where Buildx is required.
#    By default this action job is running 'ubuntu-latest', so it's not needed.
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
    
    # Build node image
    - name: Build node
      run: sudo ./make-image.sh -k rocky-live-node-base.ks -i superclustr-node-live

    # Build pxe image
    - name: Build pxe
      run: sudo ./make-image.sh -k rocky-live-pxe-base.ks -i superclustr-pxe-live

    # Upload node artifact
    - name: Upload node artifact
      uses: actions/upload-artifact@v2
      with:
        name: superclustr-node-live-iso
        path: out/superclustr-node-live.iso
        retention-days: 1

    # Upload pxe artifact
    - name: Upload pxe artifact
      uses: actions/upload-artifact@v2
      with:
        name: superclustr-pxe-live-iso
        path: out/superclustr-pxe-live.iso
        retention-days: 1
