name: Main

on: 
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.build_type }} Image
    runs-on: self-hosted
    strategy:
      matrix:
        build_type: ["client", "pxe"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Determine if tag push
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          echo "IS_TAG_PUSH=true" >> $GITHUB_ENV
        else
          echo "IS_TAG_PUSH=false" >> $GITHUB_ENV
        fi

    - name: Extract version from git tag or default to 'dev'
      id: get_version
      run: |
        if [[ "${IS_TAG_PUSH}" == "true" ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=dev" >> $GITHUB_OUTPUT
        fi

    - name: Build ${{ matrix.build_type }}
      run: sudo ./make-image.sh -k rocky-live-${{ matrix.build_type }}-base.ks -i rocky-live-${{ matrix.build_type }}-x86_64-${{ steps.get_version.outputs.VERSION }} -p "${{ secrets.PRIVATE_KEY }}" -d 

    - name: Upload artifact
      if: env.IS_TAG_PUSH == 'true'
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://nexus.superclustr.net
        username: ${{ secrets.NEXUS_USER }}
        password: ${{ secrets.NEXUS_PASS }}
        format: raw
        repository: superclustr-binaries
        coordinates: directory=${{ matrix.build_type }}/x86_64
        assets: filename=rocky-live-${{ matrix.build_type }}-x86_64-${{ steps.get_version.outputs.VERSION }}.iso
        filename: out/rocky-live-${{ matrix.build_type }}-x86_64-${{ steps.get_version.outputs.VERSION }}.iso
