name: Main

on: 
  push:
    branches: 
      - main

jobs:
  clean:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Delete stale artifacts
        uses: philips-labs/action-delete-artifacts@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: main.yml

  build:
    name: Build ${{ matrix.build_type }} Image
    runs-on: self-hosted
    needs: [clean]
    strategy:
      matrix:
        build_type: ["node", "pxe"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build ${{ matrix.build_type }}
      run: sudo ./make-image.sh -k rocky-live-${{ matrix.build_type }}-base.ks -i superclustr-${{ matrix.build_type }}-live -d

    # Upload to https://nexus.superclustr.net/repository/superclustr-binaries
    - name: Upload artifact to Nexus
      run: |
        curl -v -u ${{ secrets.NEXUS_USER }}:${{ secrets.NEXUS_PASS }} \
             --upload-file out/superclustr-${{ matrix.build_type }}-live.iso \
             https://nexus.superclustr.net/repository/superclustr-binaries/superclustr-${{ matrix.build_type }}-live.iso && \
             echo "Download at https://nexus.superclustr.net/repository/superclustr-binaries/superclustr-${{ matrix.build_type }}-live.iso"
      continue-on-error: true # Consider if you want the workflow to fail if this step fails
