name: Main

on: 
  push:
    branches: 
      - main

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: ['node', 'pxe']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

#    Only if you run this Job on a non amd64 image where Buildx is required.
#    By default this action job is running 'ubuntu-latest', so it's not needed.
#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
    
    - name: Build ${{ matrix.build_type }}
      run: ./make-image.sh -k rocky-live-${{ matrix.build_type }}-base -i superclustr-${{ matrix.build_type }}-live

#  deploy:
#    name: Update PXE Server
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v2
#      
#    - name: Copy files to PXE server
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.PXE_SERVER_HOST }}
#        username: ${{ secrets.PXE_SERVER_USERNAME }}
#        key: ${{ secrets.PXE_SERVER_SSH_KEY }}
#        source: "."
#        target: "/path/to/update/scripts/on/pxe/server"
#
#    - name: Update Cobbler profile on PXE server
#      uses: appleboy/ssh-action@master
#      with:
#        host: ${{ secrets.PXE_SERVER_HOST }}
#        username: ${{ secrets.PXE_SERVER_USERNAME }}
#        key: ${{ secrets.PXE_SERVER_SSH_KEY }}
#        script: |
#          cd /path/to/update/scripts/on/pxe/server
#          sudo cobbler profile remove --name=custom_profile
#          sudo cobbler profile add --name=custom_profile --distro=Rocky8.5-x86_64
#          sudo cobbler profile edit --name=custom_profile --kickstart=/path/to/your/kickstart/file
#          sudo cobbler sync
